apiVersion: v1
kind: Service
metadata:
  name: spring-service
  labels:
    app: nginx
spec:
  selector:
    app: nginx
  type: NodePort
  ports:
    - nodePort: 30001
      port: 8081
      targetPort: 8081
